import {
  Baby,
  Briefcase,
  Building2,
  Camera,
  Car,
  Church,
  Clapperboard,
  CloudSun,
  Drama,
  Film,
  GraduationCap,
  Guitar,
  Heart,
  Landmark,
  Laugh,
  Leaf,
  Mic,
  Mountain,
  Music,
  Newspaper,
  Orbit,
  Palmtree,
  PawPrint,
  Plane,
  Radio,
  Rocket,
  Shirt,
  ShoppingBag,
  Sparkles,
  Swords,
  Theater,
  Trophy,
  Tv,
  Utensils,
  Waves,
  Disc3,
  Headphones,
  Piano,
  Flame,
  Globe2,
  Sun,
  Star,
  type LucideIcon,
} from 'lucide-react';

const ICONS: Record<string, LucideIcon> = {
  // tv
  animation: Sparkles,
  auto: Car,
  business: Briefcase,
  classic: Film,
  comedy: Laugh,
  cooking: Utensils,
  culture: Landmark,
  documentary: Camera,
  education: GraduationCap,
  entertainment: Clapperboard,
  family: Heart,
  general: Tv,
  kids: Baby,
  legislative: Landmark,
  lifestyle: Shirt,
  movies: Film,
  music: Music,
  news: Newspaper,
  outdoor: Mountain,
  relax: Leaf,
  religious: Church,
  science: Rocket,
  series: Drama,
  shop: ShoppingBag,
  sports: Trophy,
  travel: Plane,
  weather: CloudSun,
  interactive: Star,
  public: Building2,
  // radio
  talk: Mic,
  pop: Star,
  rock: Guitar,
  dance: Disc3,
  jazz: Piano,
  classical: Theater,
  hiphop: Headphones,
  chill: Waves,
  oldies: Radio,
  latin: Flame,
  country: Guitar,
  world: Globe2,
  // webcams
  city: Building2,
  beach: Palmtree,
  nature: Mountain,
  wildlife: PawPrint,
  transport: Plane,
  space: Orbit,
  xxx: Swords,
};

export function categoryIcon(id: string, size = 16) {
  const I = ICONS[id] ?? Sun;
  return <I size={size} />;
}
